portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rezumeapp.urls', namespace='rezume')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'rezumeapp.views.page_404'
handler500 = 'rezumeapp.views.page_500'
# handler404 = 'rezumeapp.views.p_404'
# handler500 = 'rezumeapp.views.p_500'

rezumeapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import index, education, certificates, skills, my_projects, project_info

app_name = 'rezumeapp'

urlpatterns = [
    path('', index, name='index'),
    path('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('education/', education, name='education'),
    path('certificates/page_<int:page>/', certificates, name='certificates'),
    path('skills/', skills, name='skills'),
    # path('projects/', my_projects, name='projects_list'),
    path('projects/<int:pk>/', project_info, name='project_info'),
    # path('projects/<skill>/', my_projects, name='projects_list'),
    path('projects/page_<int:page>/<skill>/', my_projects, name='projects_list'),
]

rezumeapp/models.py
from django.db import models
from django.template.defaultfilters import slugify



TYPE_EDUCATION = (
    ('secondary', 'Среднее'),
    ('higher', 'Высшее'),
    ('additional', 'Дополнительное'),
)


# Create your models here.
# образование
class Education(models.Model):
    name_institute = models.CharField(max_length=200, verbose_name='Название уч.заведения')
    department = models.CharField(max_length=100, verbose_name='Факультет')
    specialty = models.CharField(max_length=200, verbose_name='Специальность')
    post = models.CharField(max_length=200, verbose_name='Должность', default='', blank=True)
    date_begin = models.DateField(verbose_name='Дата начала')
    date_end = models.DateField(verbose_name='Дата окончания', null=True, blank=True)
    type = models.CharField(max_length=30, verbose_name='Тип образования', choices=TYPE_EDUCATION)
    image = models.ImageField(verbose_name='Изображение диплома', upload_to='education', blank=True)
    image_descr = models.CharField(max_length=100, default='Диплом', blank=True)
    is_active = models.BooleanField(default=False, verbose_name='Удален')

    def __str__(self):
        return self.name_institute

    def get_type_ed(self):
        return self.get_type_display()


# сертификаты
class Certificates(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    name_institute = models.CharField(max_length=200, verbose_name='Название уч.заведения')
    description = models.TextField(verbose_name='Описание')
    date_end = models.DateField(verbose_name='Дата получения', null=True, blank=True)
    image = models.ImageField(verbose_name='Изображение сертификата', upload_to='certificates', blank=True)
    image_descr = models.CharField(max_length=100, default='Сертификат', blank=True)
    file = models.FileField(verbose_name='Файл сертификата', blank=True, upload_to='certificates')
    is_active = models.BooleanField(default=False, verbose_name='Удален')

    def __str__(self):
        return self.name


# навыки
class Skills(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name='Наименование')
    slug = models.SlugField(max_length=50, blank=True, verbose_name='Slug')
    # slug = models.CharField(max_length=50, unique=True)
    skills_link = models.BooleanField(default=False, verbose_name='Является ли ссылкой')
    is_active = models.BooleanField(default=False, verbose_name='Удален')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save()

    def __str__(self):
        return self.name + ' (' + self.slug + ')'




class PodSkills(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Наименование')
    slug = models.SlugField(blank=True, verbose_name='Slug')
    skills = models.ForeignKey(Skills, on_delete=models.CASCADE, verbose_name='Основной навык')
    is_active = models.BooleanField(default=False, verbose_name='Удален')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save()

    def __str__(self):
        return self.name + ' (' + self.slug + ' - ' + self.skills.name + ')'

    def get_len_podpodskills(self):
        list_podskills = PodPodSkills.objects.filter(podskills=self.pk)
        return len(list_podskills)

    def get_podpodskills(self):
        list_podpodskills = PodPodSkills.objects.filter(podskills=self.pk)
        return list_podpodskills


class PodPodSkills(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(blank=True)
    podskills = models.ForeignKey(PodSkills, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save()

    def __str__(self):
        return self.name + ' (' + self.slug + ' - ' + self.podskills.name + ')'


# проекты
class Projects(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    date_end = models.DateField(verbose_name='Дата окончания', null=True, blank=True)
    img_preview = models.ImageField(verbose_name='Картинка (превью)', upload_to='projects')
    img_preview_descr = models.CharField(max_length=100, default='preview', blank=True)
    img_1 = models.ImageField(verbose_name='Картинка 1', upload_to='projects', blank=True)
    img_1_descr = models.CharField(max_length=100, default='Картинка 1', blank=True)
    img_2 = models.ImageField(verbose_name='Картинка 2', upload_to='projects', blank=True)
    img_2_descr = models.CharField(max_length=100, default='Картинка 2', blank=True)
    img_3 = models.ImageField(verbose_name='Картинка 3', upload_to='projects', blank=True)
    img_3_descr = models.CharField(max_length=100, default='Картинка 3', blank=True)
    img_4 = models.ImageField(verbose_name='Картинка 4', upload_to='projects', blank=True)
    img_4_descr = models.CharField(max_length=100, default='Картинка 4', blank=True)
    file = models.FileField(verbose_name='Файл проекта', upload_to='projects', blank=True)
    link = models.CharField(max_length=250, verbose_name='Ссылка на проект', blank=True)
    skills = models.ManyToManyField(PodSkills, blank=True)
    podskills = models.ManyToManyField(PodPodSkills, blank=True)
    is_active = models.BooleanField(default=False, verbose_name='Удален')

    def __str__(self):
        return self.name

rezumeapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, render_to_response, get_object_or_404
from authapp.models import MyUser
from .models import Education, Certificates, Skills, PodSkills, PodPodSkills, Projects
# Create your views here.


def page_404(request, exception):
    user_info = MyUser.objects.get(username='bear_chaos')
    context = {
        'user_info': user_info
    }
    return render(request, '404.html', context, status=404)


def page_500(request):
    user_info = MyUser.objects.get(username='bear_chaos')
    context = {
        'user_info': user_info
    }
    return render(request, '500.html', context, status=500)


# главная
def index(request):
    user_info = MyUser.objects.get(username='bear_chaos')
    context = {
        'user_info': user_info
    }
    return render(request, 'rezumeapp/index.html', context)


# образование
def education(request):
    education_list = Education.objects.all().order_by('date_end')
    user_info = MyUser.objects.get(username='bear_chaos')
    context = {
        'education_list': education_list,
        'user_info': user_info,
    }
    return render(request, 'rezumeapp/education.html', context)


# сертификаты
def certificates(request, page=1):
    user_info = MyUser.objects.get(username='bear_chaos')
    certificate_list = Certificates.objects.filter(is_active=False).order_by('-date_end')
    paginator = Paginator(certificate_list, 4)
    try:  # получение объектов нужной страницы
        certificate_paginator = paginator.page(page)
    except PageNotAnInteger:
        certificate_paginator = paginator.page(1)
    except EmptyPage:  # последняя страница
        certificate_paginator = paginator.page(paginator.num_pages)

    context = {
        # 'certificate_list': certificate_list,
        'certificate_list': certificate_paginator,
        'user_info': user_info,
    }
    return render(request, 'rezumeapp/certifikate.html', context)


# навыки
def skills(request):
    skills_list = Skills.objects.all()
    podskills_list = PodSkills.objects.filter(is_active=False)
    user_info = MyUser.objects.get(username='bear_chaos')
    context = {
        'skills_list': skills_list,
        'podskills_list': podskills_list,
        'user_info': user_info,
    }
    return render(request, 'rezumeapp/skills.html', context)


# проекты
def my_projects(request, page=1, skill='all'):
    user_info = MyUser.objects.get(username='bear_chaos')
    if skill != 'all':
        projects_list = Projects.objects.filter(skills__slug=skill, is_active=False).order_by('-date_end')
        if len(projects_list) == 0:
            projects_list = Projects.objects.filter(podskills__slug=skill).order_by('-date_end')
    else:
        projects_list = Projects.objects.filter(is_active=False).order_by('-date_end')

    paginator = Paginator(projects_list, 3)
    try:
        projects_paginator = paginator.page(page)
    except PageNotAnInteger:
        projects_paginator = paginator.page(1)
    except EmptyPage:
        projects_paginator = paginator.page(paginator.num_pages)
    context = {
        'user_info': user_info,
        'projects_list': projects_paginator,
        'projects_page_skill': skill,
        # 'projects_list': projects_list,
    }
    return render(request, 'rezumeapp/projects_list.html', context)
# def my_projects(request, skill='all'):
#     user_info = MyUser.objects.get(username='bear_chaos')
#     if skill != 'all':
#         projects_list = Projects.objects.filter(skills__slug=skill, is_active=False).order_by('-date_end')
#         if len(projects_list) == 0:
#             projects_list = Projects.objects.filter(podskills__slug=skill).order_by('-date_end')
#     else:
#         projects_list = Projects.objects.filter(is_active=False).order_by('-date_end')
#     context = {
#         'user_info': user_info,
#         'projects_list': projects_list,
#     }
#     return render(request, 'rezumeapp/projects_list.html', context)

# def my_projects(request, skill):
#     user_info = MyUser.objects.get(username='bear_chaos')
#     projects_list = Projects.objects.all().order_by('-date_end')
#     context = {
#         'user_info': user_info,
#         'projects_list': projects_list,
#     }
#     return render(request, 'rezumeapp/projects_list.html', context)


# проект
def project_info(request, pk):
    user_info = MyUser.objects.get(username='bear_chaos')
    project = get_object_or_404(Projects, pk=pk)
    context = {
        'user_info': user_info,
        'project_info': project,
    }
    return render(request, 'rezumeapp/project.html', context)

rezumeapp/templates/rezumeapp/certifikate.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    {% include 'rezumeapp/includes/inc_short_author.html' %}
    <div class="certificate">
        <div class="certificate_main">
            {% for certificate in certificate_list %}
                <div class="certificate_block">
                   <div class="certificate_main_block"><img src="{{ certificate.image.url }}" alt="{{ certificate.image_descr }}" class="img_certificate">
                    <h2 class="edu-text">{{ certificate.name }}</h2></div>
                    <div class="certificate_hover_block">
                        <h2 class="edu-text">{{ certificate.name_institute }}</h2>
                        <h2 class="edu-text">С Е Р Т И Ф И К А Т</h2>
                        <h3 class="edu-text">{{ certificate.description }}</h3>
                        <h3 class="edu-text">{{ certificate.date_end|date:"j.m.Y" }}</h3>
                        <a href="{{ certificate.image.url }}" target="_blank">Открыть</a>
                        <a href="{{ certificate.file.url }}">Скачать</a>
                    </div>
                </div>
            {% empty %}
                <div class="certificate_block">
                    <h2>Сертификаты отсутствуют.</h2>
                </div>
            {% endfor %}
        </div>
        {% if certificate_list.paginator.num_pages > 1 %}
            <div class="pagination">
                {% if certificate_list.has_previous %}
                    <a href="{% url 'rezume:certificates' certificate_list.previous_page_number %}">&laquo;</a>
                {% endif %}
                {{ certificate_list.number }} из {{ certificate_list.paginator.num_pages }}
                {% if certificate_list.has_next %}
                    <a href="{% url 'rezume:certificates' certificate_list.next_page_number %}">&raquo;</a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

rezumeapp/templates/rezumeapp/education.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    {% include 'rezumeapp/includes/inc_short_author.html' %}
    <div class="education">
        {% for education in education_list %}
            <div class="education-block">
                <div class="years">
                    {{ education.date_begin|date:"Y" }}-{{ education.date_end|date:"Y" }}
                    <br>
                    {{ education.get_type_ed }}
                </div>
                <div class="education-text">
                    <h2>{{ education.name_institute }}</h2>
                    <h3><span class="edu-text">Факультет:</span> {{ education.department }}</h3>
                    <h3><span class="edu-text">Специальность:</span> {{ education.specialty }}</h3>
                    <h3><span class="edu-text">Должность:</span> {{ education.post }}</h3>
                </div>
                {% if education.image %}
                    <div class="sertificate">
                        <a href="img/sertificate_000.jpg" target="_blank"><img src="img/sertificate_000.jpg" alt=""></a>
                    </div>
                {% endif %}
            </div>
        {% empty %}
            <div class="education-block">
                <div class="education-text"><h3><span class="edu-text">Отсутствуют данные об образовании.</span></h3></div>
            </div>
        {% endfor %}
{#        <div class="education-block">#}
{#            <div class="years">2007-2012</div>#}
{#            <div class="education-text">#}
{#                <h2>Иркутский государственный технический университет</h2>#}
{#                <h3><span class="edu-text">Факультет:</span> Кибернетики</h3>#}
{#                <h3><span class="edu-text">Специальность:</span> Автоматизированная обработка и управление информацией</h3>#}
{#                <h3><span class="edu-text">Должность:</span> Инженер-программист</h3>#}
{#            </div>#}
{#<!--                        <a href="img/sertificate_000.jpg" target="_blank">-->#}
{#<!--                            <img src="img/sertificate_000.jpg" alt="">-->#}
{#<!--                        </a>-->#}
{#            <div class="sertificate">#}
{#                <a href="img/sertificate_000.jpg" target="_blank"><img src="img/sertificate_000.jpg" alt=""></a>#}
{#            </div>#}
{#        </div>#}

    </div>
{% endblock %}

rezumeapp/templates/rezumeapp/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="author">
        <div class="hover"><img class="hover_avatar" src="{{ user_info.avatar.url }}" alt="Аватар">
            <div class="hover-text">
                <h2>Добрый день!<br>Я&nbsp;рад приветствовать Вас на&nbsp;моем сайте.</h2>
                <p>Меня зовут Артур и&nbsp;я&nbsp;веб разработчик на&nbsp;Python3 + Django.</p>
                <p>За&nbsp;плечами имею небольшой опыт работы, но&nbsp;рассчитываю, что в&nbsp;ближайщем будущем ситуация улучшится. Я&nbsp;программировал на&nbsp;разных языках (java, C++, C#), но&nbsp;python увлек меня больше всех. Я&nbsp;неплохо знаком с&nbsp;реляционными базами данных. Знаком с&nbsp;графическими и&nbsp;видео-редакторами. А&nbsp;также обладаю некоторыми другими скрытыми способностями которые вы&nbsp;можете увидеть на&nbsp;странице &laquo;<a href="{% url 'rezume:skills' %}">Навыки</a>&raquo;.</p>
                <p>Я&nbsp;постоянно расширяю свои знания посредством специализированных курсов и&nbsp;чтением различной профессиональной литературы. Мне интересно программирование и&nbsp;интересно работать с&nbsp;различными данными. Каким&nbsp;бы не&nbsp;был трудным проект, начатую работу, я&nbsp;всегда доведу до&nbsp;конца.</p>
                <p>Для продолжения общения, Вы&nbsp;можете связаться со&nbsp;мной по&nbsp;контактам представленными на&nbsp;странице.</p>
                <h2>Удачного Вам дня!</h2>
            </div>
        </div>
        <div class="block-info">
            <div class="text-info">
                <h2>{{ user_info.fi }}</h2>
                <h3>{{ user_info.post }}</h3>
                <p>
                    {% if user_info.sity %}
                        г.{{ user_info.sity }}
                    {% endif %}
                    {% if user_info.birthday %}
                        &#160;&#160;&#160;{{ user_info.age }} лет
                    {% endif %}
                    {% if user_info.marital_status %}
                        &#160;&#160;&#160;{{ user_info.get_marital_status }}
                    {% endif %}
                </p>
            </div>
            <div class="contacts-info">
                <p>Контакты:</p>
                <div class="contacts-block">
                    <div class="contacts"> <img src="/static/img/contacts_icon/call.png" alt="Тел.осн.:">&#160;&#160;{{ user_info.phone1 }}</div>
                    {% if user_info.phone2 %}
                        <div class="contacts"> <img src="/static/img/contacts_icon/call.png" alt="Тел.доп.:">&#160;&#160;{{ user_info.phone2 }}</div>
                    {% endif %}
                    <div class="contacts"> <img src="/static/img/contacts_icon/gmail.png" alt="Email:">&#160;&#160;{{ user_info.email }}</div>
                    {% if user_info.telegram %}
                        <div class="contacts"> <img src="/static/img/contacts_icon/telegram.png" alt="Telegramm:">&#160;&#160;telegramm </div>
                    {% endif %}
                    {% if user_info.skype %}
                        <div class="contacts"> <img src="/static/img/contacts_icon/skype.png" alt="Skype:">&#160;&#160;archi-07-1 </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

rezumeapp/templates/rezumeapp/page404.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="page-not-found-main">
        <div class="text-info">
            <h2 class="edu-text"><span class="text-red">404 Вот так герои и погибают</span></h2> </div>
        <div class="img-info"> <img src="static/img/for_page_errors/xalk5.gif" alt=""> </div>
        <div class="text-info">
            <h2>Такой страницы не существует. Вернитесь пожалуста на <a href="#">главную</a>.</h2> </div>
    </div>
{% endblock %}

rezumeapp/templates/rezumeapp/project.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block js %}
    <script type="text/javascript">
        function showHide(element_id) {
            if (document.getElementById(element_id)) {
                var mass_id = ["img1", "img2", "img3", "img4"]
                for (var i = 0; i < mass_id.length; i++) {
                   if (document.getElementById(mass_id[i]))
                       document.getElementById(mass_id[i]).style.display = "none";
                }
                document.getElementById(element_id).style.display = "block";
            }
            else allert("Дружище! Ты требуешь от меня невозможного! Я не знаю такую картинку!");
        }
    </script>
{% endblock %}

{% block content %}
    {% include 'rezumeapp/includes/inc_short_author.html' %}
    <div class="project">
        <div class="project-name"><h2>{{ project_info.name }}</h2></div>
        {% if project_info.img_1 %}
            <div class="project-block-img">
                <a href="{{ project_info.img_1.url }}" class="img-main" target="_blank" id="img1"><img src="{{ project_info.img_1.url }}" alt="{{ project_info.img_1_descr }}"></a>
                <a href="{{ project_info.img_2.url }}" class="img-main" target="_blank" id="img2" style="display: none;"><img src="{{ project_info.img_2.url }}" alt="{{ project_info.img_2_descr }}"></a>
                <a href="{{ project_info.img_3.url }}" class="img-main" target="_blank" id="img3" style="display: none;"><img src="{{ project_info.img_3.url }}" alt="{{ project_info.img_3_descr }}"></a>
                <a href="{{ project_info.img_4.url }}" class="img-main" target="_blank" id="img4" style="display: none;"><img src="{{ project_info.img_4.url }}" alt="{{ project_info.img_4_descr }}"></a>
                <div class="img-previos">
                    <a href="javascript:void(0)" onclick="showHide('img1')" class="img-prev"><img src="{{ project_info.img_1.url }}" alt="{{ project_info.img_1_descr }}"></a>
                    <a href="javascript:void(0)" onclick="showHide('img2')" class="img-prev"><img src="{{ project_info.img_2.url }}" alt="{{ project_info.img_2_descr }}"></a>
                    <a href="javascript:void(0)" onclick="showHide('img3')" class="img-prev"><img src="{{ project_info.img_3.url }}" alt="{{ project_info.img_3_descr }}"></a>
                    <a href="javascript:void(0)" onclick="showHide('img4')" class="img-prev"><img src="{{ project_info.img_4.url }}" alt="{{ project_info.img_4_descr }}"></a>
                </div>
            </div>
        {% else %}
            <div class="project-block-img"><p>Изображения к работе осутствуют</p></div>
        {% endif %}
        <div class="project-desc">
            <p>{{ project_info.description }}</p>
        </div>
        <div class="project-info">
            {% if project_info.date_end %}
                <div class="project-close" style="color: #00ff00;">Завершен: {{ project_info.date_end|date:"j.m.Y" }}</div>
            {% else %}
                <div class="project-close">В работе</div>
            {% endif %}
            {% if project_info.link %}
                <div class="project-link">
                    <a href="{{ project_info.link }}">Перейти на страницу</a>
                </div>
            {% endif %}
            {% if project_info.file %}
                <div class="project-download">
                    <a href="{{ project_info.file.url }}">Скачать файл</a>
                </div>
            {% endif %}
        </div>
        <div class="project-skills">
            {% for skill in project_info.skills.all %}
                <a href="{% url 'rezume:projects_list' 1 skill.slug %}">{{ skill.name }}</a>
            {% endfor %}
            {% for podskill in project_info.podskills.all %}
                <a href="{% url 'rezume:projects_list' 1 podskill.slug %}">{{ podskill.name }}</a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

rezumeapp/templates/rezumeapp/projects_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    {% include 'rezumeapp/includes/inc_short_author.html' %}
        <div class="projects">
            <div class="projects-main">
                {% for project in projects_list %}
                    <div class="projects-block">
                            <a href="{% url 'rezume:project_info' project.pk %}" class="project-img-preview"><img src="{{ project.img_preview.url }}" alt="{{ project.img_preview_descr }}"></a>
                        <div class="projects-text">
                            <h2><a href="{% url 'rezume:project_info' project.pk %}">{{ project.name }}</a></h2>
                            <h3><span class="edu-text">{{ project.description|truncatechars:100 }} <a href="{% url 'rezume:project_info' project.pk %}">&#160;&#160;&#62;&#62;</a></span> </h3>
                            {% if project.date_end %}
                                <p class="text-green">Закончен {{ project.date_end|date:"j.m.Y" }}</p>
                            {% else %}
                                <p class="edu-text">В работе</p>
                            {% endif %}
                            <div class="skills">
                                {% for skill in project.skills.all %}
                                    <a href="{% url 'rezume:projects_list' 1 skill.slug %}">{{ skill.name }}</a>
                                {% endfor %}
                                {% for podskill in project.podskills.all %}
                                    <a href="{% url 'rezume:projects_list' 1 podskill.slug %}">{{ podskill.name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="projects-block">
                        <div class="projects-text">
                            <h2 class="edu-text text-center">Проекты не найдены.</h2>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if projects_list.paginator.num_pages > 1 %}
                <div class="pagination">
                    {% if projects_list.has_previous %}
                        <a href="{% url 'rezume:projects_list' projects_list.previous_page_number projects_page_skill %}">&laquo;</a>
                    {% endif %}
                    {{ projects_list.number }} из {{ projects_list.paginator.num_pages }}
                    {% if projects_list.has_next %}
                        <a href="{% url 'rezume:projects_list' projects_list.next_page_number projects_page_skill %}">&raquo;</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
{% endblock %}

rezumeapp/templates/rezumeapp/skills.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block js %}
    <script type="text/javascript">
        function showHide(element_id) {
            if (document.getElementById(element_id)) {
                var mass_id = [
                    {% for skills in skills_list %}
                        "{{ skills.slug }}",
                    {% endfor %}
                ];
                for (var i = 0; i < mass_id.length; i++) {
                   if (document.getElementById(mass_id[i]))
                       document.getElementById(mass_id[i]).style.display = "none";
                }
                document.getElementById(element_id).style.display = "block";
{#                document.getElementById(element_id).style.color = "#faebd7";#}
            }
            else allert("Элемент с id <" + element_id + "> не найден.");
        }
    </script>
{% endblock %}

{% block content %}
    {% include 'rezumeapp/includes/inc_short_author.html' %}
    <div class="skills">
        <div class="skills-block">
            <div class="list-skills">
                <ul>
                    {% for skills in skills_list %}
                        <li><a href="javascript:void(0)" onclick="showHide('{{ skills.slug }}')">{{ skills.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            {% for skills in skills_list %}
                <div class="description-skills" id="{{ skills.slug }}" {% if forloop.counter0 == 0 %}style="display: block;"{% endif %}>
                    <div class="text-skills">
                        {% for p_skills in podskills_list %}
                            {% if p_skills.skills.pk == skills.pk %}
                                <p><a href="{% url 'rezume:projects_list' 1 p_skills.slug %}">{{ p_skills.name }}</a>
                                    {% if p_skills.get_len_podpodskills > 0 %}
                                        <span class="text-podskills"> (
                                            {% for pp_skills in p_skills.get_podpodskills %}
                                                <a href="{% url 'rezume:projects_list' 1 pp_skills.slug %}">{{ pp_skills.name }}</a>
                                                {% if not forloop.last %}
                                                    ,
                                                {% endif %}
                                            {% endfor %}
                                        )
                                        </span>
                                    {% endif %}
                                </p>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}