portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rezumeapp.urls', namespace='rezume')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'rezumeapp.views.page_404'
handler500 = 'rezumeapp.views.page_500'
# handler404 = 'rezumeapp.views.p_404'
# handler500 = 'rezumeapp.views.p_500'

rezumeapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import index, education, certificates, skills, my_projects, project_info

app_name = 'rezumeapp'

urlpatterns = [
    path('', index, name='index'),
    path('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('education/', education, name='education'),
    path('certificates/page_<int:page>/', certificates, name='certificates'),
    path('skills/', skills, name='skills'),
    # path('projects/', my_projects, name='projects_list'),
    path('projects/<int:pk>/', project_info, name='project_info'),
    # path('projects/<skill>/', my_projects, name='projects_list'),
    path('projects/page_<int:page>/<skill>/', my_projects, name='projects_list'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <title>Маршалко Артур</title>
    <meta charset="UTF-8">
    <meta name="description" content="Веб-программист. Сделаю сделаю для Вас сайт под Ваши требования. В работе использую Python3 и веб-фреймворк Django.">
    <meta name="keywords" content="Маршалко, Python, Django, HTML, CSS, программист">
    <meta name="author" content="Маршалко Артур">
    <meta name="copyright" content="Маршалко Артур">
    <meta name="address" content="г.Иркутск">
	<meta name="google-site-verification" content="v1fhL_6ZrnTzmT4VGrQ9iHvyPZaePkqynK0Drzx33Cs" />
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <link rel="chortcut icon" href="/static/img/favicon.ico" type="image/x-icon">
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter49784476 = new Ya.Metrika2({
                        id:49784476,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/tag.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks2");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/49784476" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
    {% block js %}
    {% endblock %}
</head>

<body>
    <div class="container">
        <div class="content">
            <div class="header-main">
                <div class="header">
                    <div class="logo">
                        <a href="{% url 'rezume:index' %}"><img src="/static/img/logo.png" alt=""></a>
                    </div>
                    <div class="nav">
                        <ul>
                            <li><a href="{% url 'rezume:index' %}" {% if request.resolver_match.url_name == 'index' %} class="active-menu"{% endif %}>Обо мне</a></li>
                            <li><a href="{% url 'rezume:education' %}" {% if request.resolver_match.url_name == 'education' %} class="active-menu"{% endif %}>Образование</a></li>
                            <li><a href="{% url 'rezume:certificates' 1 %}" {% if request.resolver_match.url_name == 'certificates' %} class="active-menu"{% endif %}>Сертификаты</a></li>
                            <li><a href="{% url 'rezume:skills' %}" {% if request.resolver_match.url_name == 'skills' %} class="active-menu"{% endif %}>Навыки</a></li>
                            <li><a href="{% url 'rezume:projects_list' 1 'all' %}" {% if request.resolver_match.url_name == 'projects_list' or request.resolver_match.url_name == 'project_info' %} class="active-menu"{% endif %}>Проекты</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="content-main">
                {% block content %}
                {% endblock %}
            </div>

        </div>
        <footer>
            <div class="footer-main">
                <div class="footer">
                    <div class="copyright">&copy;&nbsp;2018-{% now "Y" %} Маршалко Артур. &nbsp;&nbsp;Разработка и создание сайтов.</div>
                    <div class="sociallink">
                        <a href="mailto:eurek999@gmail.com" class="sl-send"><img src="/static/img/contacts_icon/mail_off.png" alt="" class="first"><img src="/static/img/contacts_icon/mail_on.png" alt="" class="second">Написать письмо</a>
                        {% if user_info.telegram %}
                            <a href="tg://resolve?domain=nikname" class="sl-send"><img src="/static/img/contacts_icon/telegramm_off.png" alt="" class="first"><img src="/static/img/contacts_icon/telegramm_on.png" alt="" class="second">Написать в telegram</a>
                        {% endif %}
                        {% if user_info.skype %}
                            <a href="skype:{{ user_info.skype }}" class="sl-send"><img src="/static/img/contacts_icon/skype_off.png" alt="" class="first"><img src="/static/img/contacts_icon/skype_on.png" alt="" class="second">Написать в skype</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>

</html>